version: "3.8"

volumes:
  mysql_data:
  redisdata:
  prometheus_data: {}
  grafana_data: {}

services:
  mysqldb:
    build: ./db
    env_file:
      - "./db/db.env"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    command: >
      bash -c "python wait_mysql.py &&
               python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py loaddata fixture.json &&
               gunicorn backend.wsgi:application --bind 0.0.0.0:8080" &&
               
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    depends_on:
      - mysqldb
      - redis
    links:
      - mysqldb
  
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - backend

  redis:
    container_name: redis
    image: redis:latest
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - 'redisdata:/data'
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - prom_data:/prometheus
      - ./observe/prometheus/config/:/etc/prometheus/
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    command: >
      bash -c "python wait_mysql.py "&&
    depends_on:
      - prometheus
    ports:
      - 3100:3100
    volumes:
      - ./observe/grafana/grafana.ini:/etc/grafana/grafana.ini
    restart: always