# Generated by Django 4.0.6 on 2022-09-16 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Great',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('description', models.CharField(default='', max_length=200)),
                ('great_url', models.CharField(default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('similarity', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('great', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='great.great')),
            ],
            options={
                'ordering': ['updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('picture_url', models.CharField(default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('results', models.ForeignKey(db_column='result_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='great.result')),
            ],
            options={
                'ordering': ['updated_at'],
            },
        ),
    ]
