# Generated by Django 4.0.6 on 2022-09-20 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('great', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('great', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mypagegreat', to='great.great')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mypagepicture', to='great.picture')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mypageresult', to='great.result')),
            ],
            options={
                'db_table': 'mypage',
            },
        ),
    ]
