global:
  scrape_interval: 15s
  evaluation_interval: 15s

  external_labels:
    monitor: django-monitor

rule_files:
- "django.rules"

scrape_configs:
- job_name: "django"
  # metrics_path: '/abc/metrics'
  static_configs:
  - targets: ["localhost:8080"]